# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_auto_20170421_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='plannedby_user_id',
            new_name='plannedby_user',
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='user_joining_id',
            new_name='user_joining',
        ),
    ]
